StefanDoorn\SyliusAddressHouseNumberPlugin\Entity\Address:
    type: entity
    table: sylius_address
    fields:
        streetNumber:
            column: street_number
            type: string
            nullable: false
            options:
                default: ''
