StefanDoorn\SyliusStreetNumberPlugin\Entity\Address:
    type: entity
    table: sylius_address
    fields:
        streetNumber:
            column: street_number
            type: string
            nullable: false
            options:
                default: ''
        streetNumberAddition:
            column: street_number_addition
            type: string
            nullable: true
